# 2: Dataset and indexing

In [1]:
%pip install numpy
%pip install pandas
%pip install seaborn
%pip install python-terrier

Requirement already satisfied: numpy in ./anaconda3/lib/python3.13/site-packages (2.3.5)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: pandas in ./anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in ./anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in ./anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in ./anaconda3/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in ./anaconda3/lib/python3.13/site-packages (from seaborn) (2.3.5)
Requirement already satisfied: pandas>=1.2 in ./anaconda3/lib/python3.13/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in ./anaconda3/lib/python3.13/site-packages (from seaborn) (3.10.6)
Requirement already satisfied: contourpy>=1.0.1 in ./anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in ./anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in ./anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in ./anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in ./anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in ./anaconda3/lib/python3.13/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./anaconda3/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./anaconda3/lib/python3.13/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Collecting python-terrier
  Downloading python_terrier-1.0-py3-none-any.whl.metadata (987 bytes)
Collecting pyterrier>=1.0 (from pyterrier[all]>=1.0->python-terrier)
  Downloading pyterrier-1.0.4-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.13/site-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.3.5)
Requirement already satisfied: pandas<3.0 in ./anaconda3/lib/python3.13/site-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.3.3)
Requirement already satisfied: more_itertools in ./anaconda3/lib/python3.13/site-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (10.8.0)
Requirement already satisfied: tqdm in ./anaconda3/lib/python3.13/site-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.67.1)
Requirement already satisfied: requests in ./anaconda3/lib/python3.13/site-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.32.5)
Collecting ir_datasets>=0.3.2 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ir_datasets-0.5.11-py3-none-any.whl.metadata (12 kB)
Collecting deprecated (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.13/site-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.16.3)
Collecting ir_measures>=0.4.1 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ir_measures-0.4.3-py3-none-any.whl.metadata (7.0 kB)
Collecting pytrec_eval_terrier>=0.5.3 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading pytrec_eval_terrier-0.5.10-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (1.1 kB)
Requirement already satisfied: jinja2 in ./anaconda3/lib/python3.13/site-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.1.6)
Requirement already satisfied: statsmodels in ./anaconda3/lib/python3.13/site-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.14.5)
Requirement already satisfied: dill in ./anaconda3/lib/python3.13/site-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.4.0)
Requirement already satisfied: lz4 in ./anaconda3/lib/python3.13/site-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.4.5)
Requirement already satisfied: beautifulsoup4 in ./anaconda3/lib/python3.13/site-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.13.5)
Requirement already satisfied: python-dateutil>=2.8.2 in ./anaconda3/lib/python3.13/site-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./anaconda3/lib/python3.13/site-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./anaconda3/lib/python3.13/site-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2025.2)
Collecting inscriptis>=2.2.0 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading inscriptis-2.7.1-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: lxml>=4.5.2 in ./anaconda3/lib/python3.13/site-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (5.3.0)
Requirement already satisfied: pyyaml>=5.3.1 in ./anaconda3/lib/python3.13/site-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (6.0.3)
Collecting trec-car-tools>=2.5.4 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading trec_car_tools-2.6-py3-none-any.whl.metadata (640 bytes)
Collecting warc3-wet>=0.2.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading warc3_wet-0.2.5-py3-none-any.whl.metadata (2.2 kB)
Collecting warc3-wet-clueweb09>=0.2.5 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading warc3-wet-clueweb09-0.2.5.tar.gz (17 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting zlib-state>=0.1.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading zlib_state-0.1.12-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Collecting ijson>=3.1.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ijson-3.5.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting unlzw3>=0.2.1 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading unlzw3-0.2.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: pyarrow>=16.1.0 in ./anaconda3/lib/python3.13/site-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (21.0.0)
Requirement already satisfied: soupsieve>1.2 in ./anaconda3/lib/python3.13/site-packages (from beautifulsoup4->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in ./anaconda3/lib/python3.13/site-packages (from beautifulsoup4->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.15.0)
Collecting lxml>=4.5.2 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading lxml-6.0.4-cp313-cp313-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in ./anaconda3/lib/python3.13/site-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in ./anaconda3/lib/python3.13/site-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./anaconda3/lib/python3.13/site-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.13/site-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2026.4.22)
Collecting pyjnius>=1.4.2 (from pyterrier[all]>=1.0->python-terrier)
  Downloading pyjnius-1.7.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.17.0)
Collecting cbor>=1.0.0 (from trec-car-tools>=2.5.4->ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading cbor-1.0.0.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: wrapt<3,>=1.10 in ./anaconda3/lib/python3.13/site-packages (from deprecated->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./anaconda3/lib/python3.13/site-packages (from jinja2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.0.2)
Requirement already satisfied: patsy>=0.5.6 in ./anaconda3/lib/python3.13/site-packages (from statsmodels->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.0.1)
Requirement already satisfied: packaging>=21.3 in ./anaconda3/lib/python3.13/site-packages (from statsmodels->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (25.0)
Downloading python_terrier-1.0-py3-none-any.whl (1.4 kB)
Downloading pyterrier-1.0.4-py3-none-any.whl (208 kB)
Downloading ir_datasets-0.5.11-py3-none-any.whl (866 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 7.4 MB/s  0:00:00
Downloading ijson-3.5.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (149 kB)
Downloading inscriptis-2.7.1-py3-none-any.whl (45 kB)
Downloading lxml-6.0.4-cp313-cp313-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 9.5 MB/s  0:00:00 eta 0:00:01
Downloading ir_measures-0.4.3-py3-none-any.whl (61 kB)
Downloading pyjnius-1.7.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 9.8 MB/s  0:00:00
Downloading pytrec_eval_terrier-0.5.10-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (304 kB)
Downloading trec_car_tools-2.6-py3-none-any.whl (8.4 kB)
Downloading unlzw3-0.2.3-py3-none-any.whl (6.7 kB)
Downloading warc3_wet-0.2.5-py3-none-any.whl (18 kB)
Downloading zlib_state-0.1.12-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: cbor, warc3-wet-clueweb09
  Building wheel for cbor (pyproject.toml) ... done
  Created wheel for cbor: filename=cbor-1.0.0-cp313-cp313-linux_x86_64.whl size=23674 sha256=f7ec9c947e638251eed4da53e7d1421384f61cc365e61d5739a60903ed7dccbf
  Stored in directory: /home/tlvj/.cache/pip/wheels/03/01/db/836b80476f4d5f634a40b15f4121e7b095a028bd0fdc95c319
  Building wheel for warc3-wet-clueweb09 (pyproject.toml) ... done
  Created wheel for warc3-wet-clueweb09: filename=warc3_wet_clueweb09-0.2.5-py3-none-any.whl size=18998 sha256=eb7907ecc7653d7c471dbfa12001168607af233467205730efe86d0c7db07fa3
  Stored in directory: /home/tlvj/.cache/pip/wheels/89/c7/a5/fb6e58df5170b015945f3ca2f220b3fd8cfbcbfde1294aee25
Successfully built cbor warc3-wet-clueweb09
Installing collected packages: warc3-wet-clueweb09, warc3-wet, pyjnius, cbor, zlib-state, unlzw3, trec-car-tools, lxml, ijson, deprecated, pytrec_eval_terrier, inscriptis, ir_measures, ir_datasets, pyterrier, python-terrier
  Attempting uninstall: lxml
    Found existing installation: lxml 5.3.0
    Uninstalling lxml-5.3.0:
      Successfully uninstalled lxml-5.3.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/16 [python-terrier]m [pyterrier]s]
Successfully installed cbor-1.0.0 deprecated-1.3.1 ijson-3.5.0 inscriptis-2.7.1 ir_datasets-0.5.11 ir_measures-0.4.3 lxml-6.0.4 pyjnius-1.7.0 pyterrier-1.0.4 python-terrier-1.0 pytrec_eval_terrier-0.5.10 trec-car-tools-2.6 unlzw3-0.2.3 warc3-wet-0.2.5 warc3-wet-clueweb09-0.2.5 zlib-state-0.1.12
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Top-level imports
import numpy as np
import pandas as pd
import seaborn as sns
import pyterrier as pt

In [17]:
# import docs
docs = pd.read_json('/home/tlvj/msc_datalogi/2_semester/se/project_handout/lab_files/docs2.jsonl', lines=True, dtype={'docno': str})
queries = pd.read_csv('/home/tlvj/msc_datalogi/2_semester/se/project_handout/lab_files/train_queries.csv')
qrels = pd.read_csv('/home/tlvj/msc_datalogi/2_semester/se/project_handout/lab_files/train_qrels.csv')

In [18]:
print(docs.shape)
docs.sample(5, random_state=42)

(151993, 2)

          docno                                               text
114980  D114980  Leaning Tower of Pisa The tower's tilt began d...
88715    D88715  Under the Dome (novel) The semi-organized resi...
38065    D38065  The First Time Ever I Saw Your Face "The First...
16042    D16042  Pretty Little Liars Virtually all these locati...
49231    D49231  I Say a Little Prayer "I Say a Little Prayer" ...

In [19]:
print(docs['text'].iloc[2115])

My Cousin Rachel (1952 film) Twentieth Century-Fox obtained the rights to film the novel, with Burton agreeing to star in a U.S. film for the first time. Production was troubled when du Maurier and original director George Cukor were dissatisfied with the adaptation, causing Cukor to leave the project.

In [20]:
print(queries.shape)
queries.sample(5)

(10000, 2)

       qid                                               text
9310  9310  volleyball became an official sport in the sum...
170    170          where does the last name jacobo come from
8030  8030       what was the first hotel casino in las vegas
281    281              when did food stamps change to a card
1463  1463  when is revenue recognized under the completed...

In [21]:
print(qrels.shape)
qrels.sample(5)

(17746, 4)

        qid    docno  relevance  iteration
12644  4568  D108474          1          0
4990   4836   D43419          1          0
16257  7276  D139165          2          0
4822   6045   D41725          2          0
2982   8480   D26391          1          0

In [23]:
print("Unique labels: \n", qrels['relevance'].unique())
print("\n")
print("Distribution of labels: \n", qrels[['qid','relevance']].groupby(by='relevance').count().reset_index())

Unique labels:
 [2 1]


Distribution of labels:
    relevance    qid
0          1   7746
1          2  10000

In [25]:
print(qrels[qrels['relevance']==2])

        qid    docno  relevance  iteration
0       312      D15          2          0
1      6746      D31          2          0
2       272      D34          2          0
4      5963      D81          2          0
5      7532      D82          2          0
...     ...      ...        ...        ...
17739  1662  D151933          2          0
17740  4884  D151939          2          0
17742  2052  D151960          2          0
17744  3489  D151981          2          0
17745  4835  D151987          2          0

[10000 rows x 4 columns]

In [28]:
print(qrels[qrels['qid']==8030])
# Sneak peak into the query for qid 1015979
print("\nQuery")
print(queries[queries['qid']==8030]['query'].iloc[0])
# Sneak peak into document highly relevant for qid 1015979
print("\nHighly relevant text for qid 1015979")
print(docs[docs['docno']=='1015979']['text'].iloc[0])
# Sneak peak into document somwwhat relevant for qid 1015979
print("\nSomewhat relevant text for qid 1015979")
print(docs[docs['docno']=='2226456']['text'].iloc[0])

        qid    docno  relevance  iteration
14880  8030  D127677          2          0

Query

KeyError: 'query'