# 2: Dataset and indexing

In [2]:
%pip install numpy
%pip install pandas
%pip install seaborn
%pip install python-terrier

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: python-terrier in /usr/local/lib/python3.12/dist-packages (1.0)
Requirement already satisfied: pyterrier>=1.0 in /usr/local/lib/python3.12/dist-packages (from pyterrier[all]>=1.0->python-terrier) (1.0.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.0.2)
Requirement already satisfied: pandas<3.0 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.2.2)
Requirement already satisfied: more_itertools in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (10.8.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.32.4)
Requirement already satisfied: ir_datasets>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.5.11)
Requirement already satisfied: deprecated in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.3.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.16.3)
Requirement already satisfied: ir_measures>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.4.3)
Requirement already satisfied: pytrec_eval_terrier>=0.5.3 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.5.10)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.1.6)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.14.6)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.3.8)
Requirement already satisfied: lz4 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.4.5)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.13.5)
Requirement already satisfied: pyjnius>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from pyterrier[all]>=1.0->python-terrier) (1.7.0)
Requirement already satisfied: inscriptis>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.7.1)
Requirement already satisfied: lxml>=4.5.2 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (6.0.3)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (6.0.3)
Requirement already satisfied: trec-car-tools>=2.5.4 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.6)
Requirement already satisfied: warc3-wet>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.2.5)
Requirement already satisfied: warc3-wet-clueweb09>=0.2.5 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.2.5)
Requirement already satisfied: zlib-state>=0.1.3 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.1.12)
Requirement already satisfied: ijson>=3.1.3 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.5.0)
Requirement already satisfied: unlzw3>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.2.3)
Requirement already satisfied: pyarrow>=16.1.0 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (18.1.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2026.2.25)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.0.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (26.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.17.0)
Requirement already satisfied: cbor>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from trec-car-tools>=2.5.4->ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.0.0)

In [22]:
# Top-level imports
import numpy as np
import pandas as pd
import seaborn as sns
import pyterrier as pt

In [23]:
# import docs
base = 'https://raw.githubusercontent.com/Legenden84/search-engines/master/project_handout/lab_files'

docs    = pd.read_json(f'{base}/docs2.jsonl', lines=True, dtype={'docno': str})
queries = pd.read_csv(f'{base}/train_queries.csv')
qrels   = pd.read_csv(f'{base}/train_qrels.csv')

In [24]:
print(docs.shape)
docs.sample(5, random_state=42)

(151993, 2)

          docno                                               text
114980  D114980  Leaning Tower of Pisa The tower's tilt began d...
88715    D88715  Under the Dome (novel) The semi-organized resi...
38065    D38065  The First Time Ever I Saw Your Face "The First...
16042    D16042  Pretty Little Liars Virtually all these locati...
49231    D49231  I Say a Little Prayer "I Say a Little Prayer" ...

In [25]:
print(docs['text'].iloc[2115])

My Cousin Rachel (1952 film) Twentieth Century-Fox obtained the rights to film the novel, with Burton agreeing to star in a U.S. film for the first time. Production was troubled when du Maurier and original director George Cukor were dissatisfied with the adaptation, causing Cukor to leave the project.

In [26]:
print(queries.shape)
queries.sample(5)

(10000, 2)

       qid                                              text
6813  6813   who has ian beale been married to in eastenders
1596  1596  who does michael scott end up with on the office
2464  2464             where do beans go on the food pyramid
4866  4866             who died in agents of shield season 3
3898  3898          what is pepper's real name from iron man

In [27]:
print(qrels.shape)
qrels.sample(5)

(17746, 4)

        qid    docno  relevance  iteration
4406   1868   D38189          2          0
12003  8187  D103144          1          0
15618  6945  D133707          2          0
11669  2539  D100216          1          0
17637  5230  D151054          2          0

In [28]:
print('Unique labels: \n', qrels['relevance'].unique())
print('\n')
print('Distribution of labels: \n', qrels[['qid','relevance']].groupby(by='relevance').count().reset_index())

Unique labels:
 [2 1]


Distribution of labels:
    relevance    qid
0          1   7746
1          2  10000

In [29]:
print(qrels[qrels['relevance'] == 2])

        qid    docno  relevance  iteration
0       312      D15          2          0
1      6746      D31          2          0
2       272      D34          2          0
4      5963      D81          2          0
5      7532      D82          2          0
...     ...      ...        ...        ...
17739  1662  D151933          2          0
17740  4884  D151939          2          0
17742  2052  D151960          2          0
17744  3489  D151981          2          0
17745  4835  D151987          2          0

[10000 rows x 4 columns]

In [30]:
qid = 8030

# Sneak peak into the query for qid D127677
qrels_for_qid = qrels[qrels['qid'] == qid]
print(qrels_for_qid)

# Sneak peak into document highly relevant for qid D127677
print('\nQuery')
print(queries.loc[queries['qid'] == qid, 'text'].iloc[0])

# Sneak peak into document somwwhat relevant for qid D127677
docno = qrels_for_qid.sort_values('relevance', ascending=False)['docno'].iloc[0]

print(f'\nRelevant document for qid {qid}: {docno}')
print(docs.loc[docs["docno"] == docno, "text"].iloc[0])

        qid    docno  relevance  iteration
14880  8030  D127677          2          0

Query
what was the first hotel casino in las vegas

Relevant document for qid 8030: D127677
Prem Ratan Dhan Payo Prem Ratan Dhan Payo (English: Found a Treasure Called Love) is a 2015 Indian romantic drama film[4] written and directed by Sooraj Barjatya, produced by Rajshri Productions and distributed by Fox Star Studios. It stars Salman Khan and Sonam Kapoor in lead roles.[5] This is the fourth collaboration between Barjatya and Khan after their previous films Maine Pyar Kiya, Hum Aapke Hain Koun..!, and Hum Saath Saath Hain.

In [31]:
qrels['iteration'].unique()

array([0])

In [38]:
# Query statistics
query_statistics = queries["text"].str.split().str.len()

res = pd.DataFrame({
    "min": [query_statistics.min()],
    "max": [query_statistics.max()],
    "median": [query_statistics.median()],
    "average": [query_statistics.mean()]
}, index=["query_statistics"])

res

                  min  max  median  average
query_statistics    5   23     9.0   9.0806

In [ ]:
ax = sns.catplot(docs, x='docno', y='doc_len', hue='doc_len', palette="ch:r=-.2,d=.3_r")
ax.tick_params(bottom=False)
ax.set(xlabel=None)

KeyboardInterrupt:

Exception ignored in: 'zmq.backend.cython._zmq.Frame.__del__'
Traceback (most recent call last):
  File "_zmq.py", line 160, in zmq.backend.cython._zmq._check_rc
KeyboardInterrupt: