In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
%%capture
!curl -s "https://get.sdkman.io" | bash && source "$HOME/.sdkman/bin/sdkman-init.sh" && sdk install java 11.0.22-amzn < /dev/null

In [3]:
!pip install python-terrier

Collecting python-terrier
  Downloading python_terrier-1.0-py3-none-any.whl.metadata (987 bytes)
Collecting pyterrier>=1.0 (from pyterrier[all]>=1.0->python-terrier)
  Downloading pyterrier-1.0.4-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.0.2)
Requirement already satisfied: pandas<3.0 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.2.2)
Requirement already satisfied: more_itertools in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (10.8.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.32.4)
Collecting ir_datasets>=0.3.2 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ir_datasets-0.5.11-py3-none-any.whl.metadata (12 kB)
Collecting deprecated (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.16.3)
Collecting ir_measures>=0.4.1 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ir_measures-0.4.3-py3-none-any.whl.metadata (7.0 kB)
Collecting pytrec_eval_terrier>=0.5.3 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading pytrec_eval_terrier-0.5.10-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (1.1 kB)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.1.6)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.14.6)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (0.3.8)
Collecting lz4 (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.13.5)
Collecting pyjnius>=1.4.2 (from pyterrier[all]>=1.0->python-terrier)
  Downloading pyjnius-1.7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting inscriptis>=2.2.0 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading inscriptis-2.7.1-py3-none-any.whl.metadata (27 kB)
Requirement already satisfied: lxml>=4.5.2 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (6.1.0)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (6.0.3)
Collecting trec-car-tools>=2.5.4 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading trec_car_tools-2.6-py3-none-any.whl.metadata (640 bytes)
Collecting warc3-wet>=0.2.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading warc3_wet-0.2.5-py3-none-any.whl.metadata (2.2 kB)
Collecting warc3-wet-clueweb09>=0.2.5 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading warc3-wet-clueweb09-0.2.5.tar.gz (17 kB)
  Preparing metadata (setup.py) ... done
Collecting zlib-state>=0.1.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading zlib_state-0.1.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.5 kB)
Collecting ijson>=3.1.3 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting unlzw3>=0.2.1 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading unlzw3-0.2.3-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: pyarrow>=16.1.0 in /usr/local/lib/python3.12/dist-packages (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (18.1.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (4.15.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2026.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2026.4.22)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (2.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (3.0.3)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (26.1)
Collecting lxml>=4.5.2 (from ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading lxml-6.0.4-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl.metadata (3.1 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3.0->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier) (1.17.0)
Collecting cbor>=1.0.0 (from trec-car-tools>=2.5.4->ir_datasets>=0.3.2->pyterrier>=1.0->pyterrier[all]>=1.0->python-terrier)
  Downloading cbor-1.0.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Downloading python_terrier-1.0-py3-none-any.whl (1.4 kB)
Downloading pyterrier-1.0.4-py3-none-any.whl (208 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 208.8/208.8 kB 9.7 MB/s eta 0:00:00
Downloading ir_datasets-0.5.11-py3-none-any.whl (866 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 866.1/866.1 kB 31.6 MB/s eta 0:00:00
Downloading ir_measures-0.4.3-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 7.3 MB/s eta 0:00:00
Downloading lz4-4.4.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 78.6 MB/s eta 0:00:00
Downloading pyjnius-1.7.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 87.7 MB/s eta 0:00:00
Downloading pytrec_eval_terrier-0.5.10-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (304 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 304.8/304.8 kB 30.5 MB/s eta 0:00:00
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading ijson-3.5.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (149 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.7/149.7 kB 16.8 MB/s eta 0:00:00
Downloading inscriptis-2.7.1-py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.6/45.6 kB 4.7 MB/s eta 0:00:00
Downloading lxml-6.0.4-cp312-cp312-manylinux_2_26_x86_64.manylinux_2_28_x86_64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 134.2 MB/s eta 0:00:0000:01
Downloading trec_car_tools-2.6-py3-none-any.whl (8.4 kB)
Downloading unlzw3-0.2.3-py3-none-any.whl (6.7 kB)
Downloading warc3_wet-0.2.5-py3-none-any.whl (18 kB)
Downloading zlib_state-0.1.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (22 kB)
Building wheels for collected packages: warc3-wet-clueweb09, cbor
  Building wheel for warc3-wet-clueweb09 (setup.py) ... done
  Created wheel for warc3-wet-clueweb09: filename=warc3_wet_clueweb09-0.2.5-py3-none-any.whl size=18919 sha256=0a7a2000b37b1629da8e20b69051cb7b320617bea8959aeb00451cde39dd8b15
  Stored in directory: /root/.cache/pip/wheels/f6/85/c2/9f0f621def52a1d5db7d29984f81e45f9fb6dfeb1a4eb6e31c
  Building wheel for cbor (setup.py) ... done
  Created wheel for cbor: filename=cbor-1.0.0-cp312-cp312-linux_x86_64.whl size=55025 sha256=33ecb0385e5f90a3c8ef09581204f1f4e13637aba5d1b23623c8988a9a825a5f
  Stored in directory: /root/.cache/pip/wheels/44/3e/21/a739cbcc331a1ab45c326d6edbdac6118de4402f6076e30ff1
Successfully built warc3-wet-clueweb09 cbor
Installing collected packages: warc3-wet-clueweb09, warc3-wet, pyjnius, cbor, zlib-state, unlzw3, trec-car-tools, lz4, lxml, ijson, deprecated, pytrec_eval_terrier, inscriptis, ir_measures, ir_datasets, pyterrier, python-terrier
  Attempting uninstall: lxml
    Found existing installation: lxml 6.1.0
    Uninstalling lxml-6.1.0:
      Successfully uninstalled lxml-6.1.0
Successfully installed cbor-1.0.0 deprecated-1.3.1 ijson-3.5.0 inscriptis-2.7.1 ir_datasets-0.5.11 ir_measures-0.4.3 lxml-6.0.4 lz4-4.4.5 pyjnius-1.7.0 pyterrier-1.0.4 python-terrier-1.0 pytrec_eval_terrier-0.5.10 trec-car-tools-2.6 unlzw3-0.2.3 warc3-wet-0.2.5 warc3-wet-clueweb09-0.2.5 zlib-state-0.1.12

# SE 2025 - Lab 5: Query Expansion with LLMs

In [4]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)
from pprint import pprint

# To use LLMs
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

# To use Evalutaion Metrics
from pyterrier.measures import *

# To use GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [5]:
# Confirm GPU utilization
print(device)

cuda

## The Dataset

First, we will introduce the dataset. In our labs, we will be using a subset of the small version of [WikIR](https://www.aclweb.org/anthology/2020.lrec-1.237.pdf) dataset for English.

Download the following files (available also on Absalon under folder `lab`) in a folder called `data/`:
- [`lab_docs.csv`](https://absalon.instructure.com/files/7103632/download?download_frd=1): CSV file of document number and document text
- [`lab_topics.csv`](https://absalon.instructure.com/files/7103631/download?download_frd=1): CSV file of query id and query text
- [`lab_qrels.csv`](https://absalon.instructure.com/files/7103630/download?download_frd=1): CSV file of annotations with schema `qid, docno, label, iteration`

In [9]:
base = 'https://raw.githubusercontent.com/Legenden84/search-engines/master/lab_test'

docs = pd.read_csv(f'{base}/lab_docs.csv', dtype={'docno': str, 'text': str})
topics = pd.read_csv(f'{base}/lab_topics.csv', dtype={'qid': str})
qrels = pd.read_csv(f'{base}/lab_qrels.csv', dtype={'qid': str, 'docno': str, 'label': int})

## Systems Setup

We will start by building an index of our data collection and a few systems in PyTerrier.
This step is only required to obtain system outputs.

In [10]:
%env JAVA_HOME=/root/.sdkman/candidates/java/current
import pyterrier as pt
if not pt.started():
    pt.init()

env: JAVA_HOME=/root/.sdkman/candidates/java/current
terrier-assemblies 5.11 jar-with-dependencies not found, downloading to /root/.pyterrier...

/tmp/ipykernel_3693/2062180214.py:3: DeprecationWarning: Call to deprecated function (or staticmethod) started. (use pt.java.started() instead) -- Deprecated since version 0.11.0.
  if not pt.started():

https://repo1.maven.org/maven2/org/terrier/terrier-assemblies/5.11/terrier-assemblies-5.11-jar-with-dependenci…

Done
terrier-python-helper 0.0.8 jar not found, downloading to /root/.pyterrier...

https://repo1.maven.org/maven2/org/terrier/terrier-python-helper/0.0.8/terrier-python-helper-0.0.8.jar:   0%| …

Done

Java started and loaded: pyterrier.java.colab, pyterrier.java, pyterrier.java.24, pyterrier.terrier.java [version=5.11 (build: craig.macdonald 2025-01-13 21:29), helper_version=0.0.8]
/tmp/ipykernel_3693/2062180214.py:4: DeprecationWarning: Call to deprecated method pt.init(). Deprecated since version 0.11.0.
java is now started automatically with default settings. To force initialisation early, run:
pt.java.init() # optional, forces java initialisation
  pt.init()

In [11]:
# Build index
indexer = pt.IterDictIndexer("./indexes/pt_index_default", overwrite=True, blocks=True)
index_ref = indexer.index(docs.to_dict(orient='records'))
index = pt.IndexFactory.of(index_ref)
print(index.getCollectionStatistics().toString())

Number of documents: 2453
Number of terms: 23693
Number of postings: 208487
Number of fields: 0
Number of tokens: 273373
Field names: []
Positions:   true

## Baselines: BM25 and TF-IDF

Evaluate default BM25 and TF-IDF models from PyTerrier:

In [12]:
# Build SEs
TF_IDF = pt.terrier.Retriever(index, wmodel="TF_IDF")
BM25 = pt.terrier.Retriever(index, wmodel="BM25")

In [13]:
# Evaluate systems on the topics using the PyTerrier Experiment interface
bm25_tfidf = pt.Experiment(
    retr_systems=[TF_IDF, BM25],
    names=['TF-IDF', 'BM25'],
    topics=topics,
    qrels=qrels,
    eval_metrics=[nDCG@10, P@10, R@10],
    round=4 # round to 4 decimal places
)

bm25_tfidf

     name    P@10    R@10  nDCG@10
0  TF-IDF  0.7667  0.3869   0.8408
1    BM25  0.7667  0.3869   0.8425

## Using LLMs for Query Expansion

In this small dataset, BM25 and TF-IDF have similar performances. Let's see how we can leverage LLMs for query expansion. There are three different approaches we can take[^1]:
* Zero-shot prompting
* Few-shot prompting
* Chain-of-thought prompting

In this lab we will look at zero-shot and few-shot prompting.

[^1]: [Query Expansion by Prompting Large Language Models](https://arxiv.org/pdf/2305.03653)

### Zero-shot prompting: No exemplars given - Just enter your query

Prompt: Write a passage that answers the following query: <#query-goes-here>
Passage: <#LLM-output>

```
We can consider the output of the LLM as a relevant document *d* and use it *as-is* to expand the original query:

q' = Concat(q, *d*)
```

For this lab, we use Qwen3-1.7B, a 1.7 Billion Parameter LM. More details on [huggingface](https://huggingface.co/Qwen/Qwen3-1.7B)

In [14]:
# We can achieve something similar to above by using huggingface transformer library

# Load pre-trained model
model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen3-1.7B",
                                             torch_dtype=torch.float16, # 16 bit - helps with memory management
                                             device_map=device,
                                             trust_remote_code=True)

# Load pre-trained tokenizer
tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3-1.7B")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:103: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(

config.json:   0%|          | 0.00/726 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Downloading (incomplete total...): 0.00B [00:00, ?B/s]

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/311 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.embed_tokens.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

In [19]:
# Select a random query

query = topics.sample(n=1, random_state=42)['query'].iloc[0]
prompt = f'Generate key words for adding terms to a query expansion: {query} \nAnswer:'

print(query)
print(prompt)

house
Generate key words for adding terms to a query expansion: house
Answer:

In [20]:
# Tokenize the input
# Attention mask: Tell the model which tokens should be attended to (usually 1) and which are just padding (usually 0).
#                 Essential when you're batching sequences of different lengths.

inputs = tokenizer(prompt, return_tensors="pt", return_attention_mask=True)
print(inputs)
print(inputs['input_ids'].shape)

{'input_ids': tensor([[31115,  1376,  4244,   369,  7842,  3793,   311,   264,  3239, 14461,
            25,  3753,   715, 16141,    25]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}
torch.Size([1, 15])

In [21]:
# Generate output tokens
# max_length: How many max_tokens to generate. This includes number of tokens from the inputß

outputs = model.generate(inputs.input_ids.to(device), max_length=50)
print(outputs)
print(outputs.shape)

tensor([[31115,  1376,  4244,   369,  7842,  3793,   311,   264,  3239, 14461,
            25,  3753,   715, 16141,    25,   576,  2701,   525,   279,  1376,
          4244,   369,  7842,  3793,   311,   264,  3239, 14461,   369,   279,
          4647,   330,  7675, 51418,    16,    13,  3753,   198,    17,    13,
          3753,   304,   198,    18,    13,  3753,   369,   198,    19,    13]],
       device='cuda:0')
torch.Size([1, 50])

In [22]:
# Decode output tokens

text = tokenizer.batch_decode(outputs)[0]
pprint(text)

('Generate key words for adding terms to a query expansion: house \n'
 'Answer: The following are the key words for adding terms to a query '
 'expansion for the term "house":\n'
 '\n'
 '1. house\n'
 '2. house in\n'
 '3. house for\n'
 '4.')

The length of the produced output is much higher than the query length and the query term frequencies might be much lower compared to the terms of the LLM output, downplaying the importance of the original query. We can combat this by:

```
q' = Concat({q} x 5, *d*)
```

*Note that LLM outputs are non-deterministic until you specify temperature=0*

In [23]:
expanded_query = ' '.join([query] * 5) + ' ' + text
expanded_query

'house house house house house Generate key words for adding terms to a query expansion: house \nAnswer: The following are the key words for adding terms to a query expansion for the term "house":\n\n1. house\n2. house in\n3. house for\n4.'

In [24]:
%%time

# Lets expand all the queries
zeroshot_topics = topics.copy(True)
expanded_queries = []

# Note: Batching inputs will speed up the process. This code does not batch the inputs.
for query in topics['query'].values:
    # Prompt for LLM
    prompt = f'Write a passage that answers the following query: {query} \nAnswer:'
    print("PROMPT")
    print(prompt)
    inputs = tokenizer(prompt, return_tensors="pt", return_attention_mask=False)
    outputs = model.generate(inputs.input_ids.to(device), max_new_tokens=50)
    # Extract text after prompt ends
    text = tokenizer.batch_decode(outputs)[0][len(prompt) + 1:]
    # sanitize for punctuation
    text = ''.join([x for x in text if x.isalnum() or x.isspace()])
    print("GENERATED TEXT")
    print(text)
    print("==" * 60)
    expanded_queries.append(' '.join([query] * 5) + ' ' + text)
zeroshot_topics.loc[:, 'query'] = expanded_queries

PROMPT
Write a passage that answers the following query: president of chile
Answer:
GENERATED TEXT
the president of chile is michelina hidalgo who is the first woman to serve as president of chile and has served in this role since 2010

Make sure that the passage is in the first person
========================================================================================================================
PROMPT
Write a passage that answers the following query: computer animation
Answer:
GENERATED TEXT
The computer animation is a type of animation that uses computer software to create images and videos It is used in various fields such as film television video games and virtual reality Computer animation is a complex process that involves the creation of 2
========================================================================================================================
PROMPT
Write a passage that answers the following query: 2020 summer olympics
Answer:
GENERATED TEXT
2020 summer olympics took place in which city and country

Okay I need to answer the question about where the 2020 Summer Olympics took place Let me think I remember that the 202
========================================================================================================================
PROMPT
Write a passage that answers the following query: train station
Answer:
GENERATED TEXT
1 The train station is located in the center of the city surrounded by a wide green park 2 The station is the main hub for the citys transportation connecting the city with other parts of the country 3
========================================================================================================================
PROMPT
Write a passage that answers the following query: chinese cuisine
Answer:
GENERATED TEXT
the food in china is diverse and varied with many different regional cuisines for example the food in the north of china is different from the food in the south in addition to the traditional chinese cuisine there are also many other types of
========================================================================================================================
PROMPT
Write a passage that answers the following query: world war ii
Answer:
GENERATED TEXT
The war started in 1939 with Germany invading Poland and then the UK and France declared war on Germany The war ended in 1945 with the surrender of Nazi Germany and the Allied forces It was a global conflict involving
========================================================================================================================
PROMPT
Write a passage that answers the following query: painting
Answer:
GENERATED TEXT
The painting The Persistence of Memory by Salvador Dalí is a famous example of surrealist art It is known for its melting clocks and dreamlike imagery The painting was created in 1931 and is housed in the Gugg
========================================================================================================================
PROMPT
Write a passage that answers the following query: house
Answer:
GENERATED TEXT
The house is a building typically with a roof walls and a foundation designed to provide shelter and housing for people or animals It is a fundamental element of human habitation and has been used for centuries to provide a safe and comfortable living
========================================================================================================================
PROMPT
Write a passage that answers the following query: mexican cuisine
Answer:
GENERATED TEXT
The cuisine of Mexico is a vibrant blend of indigenous and Spanish influences with a rich array of flavors and ingredients It is known for its use of fresh locally sourced produce and the incorporation of traditional cooking methods Mexican food is characterized by its bold
========================================================================================================================
CPU times: user 23.7 s, sys: 14.8 ms, total: 23.7 s
Wall time: 23.8 s

In [25]:
zeroshot_topics

       qid                                              query
0  1015979  president of chile president of chile presiden...
1     2674  computer animation computer animation computer...
2   340095  2020 summer olympics 2020 summer olympics 2020...
3  1502917  train station train station train station trai...
4     2574  chinese cuisine chinese cuisine chinese cuisin...
5    14082  world war ii world war ii world war ii world w...
6  1250390  painting painting painting painting painting T...
7     5597  house house house house house The house is a b...
8     8438  mexican cuisine mexican cuisine mexican cuisin...

In [26]:
pprint(zeroshot_topics['query'].iloc[0])
print("========================================================================")
pprint(zeroshot_topics['query'].iloc[3])

('president of chile president of chile president of chile president of chile '
 'president of chile the president of chile is michelina hidalgo who is the '
 'first woman to serve as president of chile and has served in this role since '
 '2010\n'
 '\n'
 'Make sure that the passage is in the first person')
========================================================================
('train station train station train station train station train station 1 The '
 'train station is located in the center of the city surrounded by a wide '
 'green park 2 The station is the main hub for the citys transportation '
 'connecting the city with other parts of the country 3')

In [27]:
zeroshot_bm25 = pt.Experiment([BM25],
                              names=['zeroshot >> BM25'],
                              topics=zeroshot_topics,
                              qrels=qrels,
                              eval_metrics=[nDCG@10, P@10, R@10],
                              round=4) # round to 4 decimal places)

pd.concat((bm25_tfidf, zeroshot_bm25), ignore_index=True)

               name    P@10    R@10  nDCG@10
0            TF-IDF  0.7667  0.3869   0.8408
1              BM25  0.7667  0.3869   0.8425
2  zeroshot >> BM25  0.7556  0.3663   0.8322

Did Query Expansion help? Why/Why Not?

Any guesses why?

## Zero-shot with Pseudo-Relevance-Feedback : Add context

We pass 2 pseudo-relevant documents from a BM25 retrieval as context:

In [28]:
%%time

# 1. Batch retrieve for ALL topics at once
retrieval_results = BM25.transform(topics)

# 2. Pre-index docs
docs_indexed = docs.set_index('docno')

expanded_queries = []

# 3. Process each query
for qid, query in zip(topics['qid'].values, topics['query'].values):

    # Filter batch results for the current query and get top 2
    query_res = retrieval_results[retrieval_results['qid'] == qid].head(2)
    top2_docno = query_res['docno'].values

    # Safely fetch text in exact rank order (ignore missing docs just in case)
    top2_text = docs_indexed.loc[docs_indexed.index.intersection(top2_docno), 'text'].values

    # Build prompt
    context = "\n".join(top2_text)
    prompt = f"Write a passage that answers the given query based on the context: {query}\nContext:\n{context}\nQuery: {query}\nAnswer:"
    print("PROMPT")
    print(prompt)
    print("\n")
    # Generate
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    outputs = model.generate(**inputs, max_new_tokens=50, pad_token_id=tokenizer.eos_token_id)

    # Clean decode
    input_len = inputs.input_ids.shape[1]
    gen_text = tokenizer.decode(outputs[0][input_len:], skip_special_tokens=True)
    cleaned_text = ''.join([x for x in gen_text if x.isalnum() or x.isspace()])

    print("GENERATED TEXT")
    print(cleaned_text)
    print("=" * 60)
    # Pseudo-Relevance Feedback query weighting
    expanded_queries.append(' '.join([query] * 5) + ' ' + cleaned_text)

# Assign back safely using a new copy
zeroshot_prf_topics = topics.copy()
zeroshot_prf_topics['query'] = expanded_queries

PROMPT
Write a passage that answers the given query based on the context: president of chile
Context:
the president is responsible for both the chilean government and state administration although its role and significance has changed over the history of chile as well as its position and relations with other actors in the national political organization it is one of the most prominent political figures it is also considered as one of the institutions that make up the historic constitution of chile and is essential to the country s political stability under the current constitution adopted in 1980 the president serves a four year term with immediate re election being prohibited the shorter period previously the term was six years allows for parliamentary and presidential elections to be synchronized the official seat of the president of chile is the la moneda palace in the capital santiago the constitution of 1980 and its 2005 amendment establishes the requirements for becoming president the president must be a natural born citizen of the country or else born overseas when one of his or her parents or grandparents is a chilean national the president must also be at least 35 years old in addition all the requirements for becoming a senator apply the president must meet all the requirements to qualify
the war saw a confrontation between the chilean army and the chilean navy which sided with the president and the congress respectively this conflict ended with the defeat of the chilean army and the presidential forces and president balmaceda committing suicide as a consequence in chilean historiography the war marks the end of the liberal republic and the beginning of the parliamentary era the chilean civil war grew out of political disagreements between the president of chile jos manuel balmaceda and the chilean congress in 1889 the congress became distinctly hostile to the administration of president balmaceda and the political situation became serious at times threatened to involve the country in civil war according to usage and custom in chile at the time a minister could not remain in office unless supported by a majority in the chambers balmaceda found himself in the difficult position of being unable to appoint any ministers that could control a majority in the senate and chamber of deputies and at the same time be in accordance with his own views of the administration of public affairs at this juncture the president assumed that the constitution gave him the power of nominating and maintaining in
Query: president of chile
Answer:


GENERATED TEXT
 The president of Chile is a key political figure in the countrys governance serving as the head of state and head of government The president is responsible for leading the Chilean government and managing state administration though their role and significance have evolved over time
============================================================
PROMPT
Write a passage that answers the given query based on the context: computer animation
Context:
the more general term computer generated imagery cgi encompasses both static scenes and dynamic images while computer animation only refers to moving images modern computer animation usually uses 3d computer graphics although 2d computer graphics are still used for stylistic low bandwidth and faster real time renderings sometimes the target of the animation is the computer itself but sometimes film as well computer animation is essentially a digital successor to stop motion techniques but using 3d models and traditional animation techniques using frame by frame animation of 2d illustrations computer generated animations are more controllable than other more physically based processes like constructing miniatures for effects shots or hiring extras for crowd scenes because it allows the creation of images that would not be feasible using any other technology it can also allow a single graphic artist to produce such content without the use of actors expensive set pieces or props to create the illusion of movement an image is displayed on the computer monitor and repeatedly replaced by a new image that is similar to it but advanced slightly in time usually at a rate of 24 25 or 30 frames second this technique is identical to how the
the film tells the story of an aardvark who becomes the leader of a group of misfit animals in order to bring all the animals onto noah s ark the film stars the voices of miles teller aubrey plaza jenny slate rob riggle craig robinson and stephen merchant the story follows an outcast aardvark by the name of gilbert who becomes the reluctant leader of a ragtag group of misfit animals that need to be led to the mighty ark before the impending flood along their journey they band together to conquer unforeseen obstacles and ultimately gilbert discovers within himself the inner strength and ingenuity to prove that in a world of twos he was truly destined to be the one on october 1 2007 it was announced that unified pictures would produce a 35 million budgeted computer animated film noah s ark which philip lazebnik would write the screenplay with electroage handling the animation in march 2013 the studio hired kung fu panda s director john stevenson to handle the creative work on the film with cameron hood as co director while later on august 20 2014 it was reported that stevenson had been hired as the director of
Query: computer animation
Answer:


GENERATED TEXT
 The term computer animation refers to the process of creating moving images using computergenerated imagery CGI It involves the use of 3D computer graphics although 2D graphics are also employed for stylistic effects Computer animation is a digital successor
============================================================
PROMPT
Write a passage that answers the given query based on the context: 2020 summer olympics
Context:
since the nation s debut in 1952 israeli athletes have appeared in every edition of the summer olympic games other than the 1980 summer olympics in moscow which it opted not to attend because of the nation s support for the us led boycott it will be israel s 17th appearance at the summer olympics a total of 47 israeli athletes 22 men and 25 women traveled to the rio de janeiro 2016 olympics and competed across 17 sports it was israel s largest ever delegation sent to the olympics breaking its previous record of 43 athletes set in 2008 that record is set to be broken in 2020 with 51 confirmed athletes as of october 2019 among the sports in which its athletes will compete israel will mark its olympic debut in surfing new to the 2020 games baseball returning to the 2020 games and equestrian the israeli delegation so far includes 51 athletes competing in 9 sports four israeli athletes achieved the entry standards by qualifying time in the following track and field events the olympic committee of israel has not yet released the names of athletes to participate in the delegation the national baseball team of israel
this will be the second time that tokyo has hosted the summer olympic games the first being in 1964 and the fourth olympics to be held in japan which also hosted the winter olympics in 1972 sapporo and 1998 nagano the 2020 games will be the second of three consecutive olympics to be held in east asia the first being the 2018 winter olympics in pyeongchang county south korea and the next being the 2022 winter olympics in beijing china these games will see the introduction of new and additional competitions at the summer olympics including 3x3 basketball freestyle bmx and madison cycling as well as further mixed events under new ioc policies that allow the host organizing committee to add sports to the olympic programme to augment the permanent core olympic events these games will see karate sport climbing surfing and skateboarding make their olympic debuts there will also be the return of baseball and softball both removed from the summer programme after 2008 tokyo istanbul and madrid were the three candidate cities the applicant cities of baku azerbaijan and doha qatar were not promoted to candidate status a bid from rome was withdrawn the ioc voted to select
Query: 2020 summer olympics
Answer:


GENERATED TEXT
 The 2020 Summer Olympics held in Tokyo Japan marked a significant milestone for Israel with its athletes making history by competing in the countrys debut in surfing which was added to the program Israel had previously participated in every
============================================================
PROMPT
Write a passage that answers the given query based on the context: train station
Context:
the station is located at kilometric point 20 741 of paris est mulhouse ville railway and is nearby the town of le plessis tr vise hence its name opened on the paris est mulhouse ville railway the station is served since august 30 1999 by trains of the line going through the e4 branch it was previously served by suburban trains logotype from gare de l est since 1857 initially one of the general terminus of the line the station became a partial terminus for 4 trains out of 6 at off peak times and 1 train out of 2 at peak hours with the extension of this line to tournan on december 14 2003 in 2016 the estimated annual attendance by sncf is 7 808 400 passengers this attendance makes this station the 5th busiest station in val de marne d partement there are approximately 120 trains per working day in each direction between paris haussmann saint lazare and villiers sur marne station the first train of the service leaves for paris at 5 04 am and the last train of the service arrives from paris at 1 25 am these schedules are valid every day of the year
it generally consists of at least one track side platform and a station building depot providing such ancillary services as ticket sales and waiting rooms if a station is on a single track line it often has a passing loop to facilitate traffic movements the smallest stations are most often referred to as stops or in some parts of the world as halts flag stops stations may be at ground level underground or elevated connections may be available to intersecting rail lines or other transport modes such as buses trams or other rapid transit systems in british english traditional usage favours railway station or simply station even though train station which is often perceived as an americanism is now about as common as railway station in writing railroad station is not used railroad being obsolete there in british usage the word station is commonly understood to mean a railway station unless otherwise qualified in american english the most common term in contemporary usage is train station railroad station and railway station are less common though they have been more common in the past in north america the term depot is sometimes used as an alternative name for station along with
Query: train station
Answer:


GENERATED TEXT
 The train station in question is located at kilometric point 20 741 of Paris Est Mulhouse Ville railway and is nearby the town of Le PlessisTrvise hence its name It was opened on this railway and
============================================================
PROMPT
Write a passage that answers the given query based on the context: chinese cuisine
Context:
while it is denser in texture than radish cakes both these savory cakes made in a similar ways with rice flour as the main ingredient when served in dim sum cuisine it is cut into square shaped slices and pan fried before serving it is found in hong kong china and overseas chinatown restaurants other ingredients often include pork and chinese black mushroom or even chinese sausages it is usually topped with chopped scallions the pan fried square taro cake is semi crunchy on the outside and medium soft on the inside it is also the most consistent version with more or less the same formula in east and southeast asia or among overseas chinese communities the other version is the more home style baked version usually it uses the same ingredients and steamed for long periods of time in a deep pan until it is ultra soft and pasty the formula varies greatly depending on the family recipe or regional tastes some restaurants offer taro cakes cut into small cubes as part of a main course appetizer to a major chinese cuisine these are sometimes frozen to a more solid state though it is not nearly as common as
because of the chinese diaspora and historical power of the country chinese cuisine has influenced many other cuisines in asia with modifications made to cater to local palates chinese food staples such as rice soy sauce noodles tea and tofu and utensils such as chopsticks and the wok can now be found worldwide the preference for seasoning and cooking techniques of chinese provinces depend on differences in historical background and ethnic groups geographic features including mountains rivers forests and deserts also have a strong effect on the local available ingredients considering that the climate of china varies from tropical in the south to subarctic in the northeast imperial royal and noble preference also plays a role in the change of chinese cuisines because of imperial expansion and trading ingredients and cooking techniques from other cultures are integrated into chinese cuisines over time the most praised four major cuisines are chuan lu yue and huaiyang representing west north south and east china cuisine correspondingly the modern eight cuisines of china are anhui hu c i cantonese yu c i fujian m nc i hunan xi ngc i jiangsu s c i shandong l c i sichuan chu nc i and zhejiang
Query: chinese cuisine
Answer:


GENERATED TEXT
 Based on the context provided Chinese cuisine is a diverse culinary tradition that encompasses a wide range of flavors techniques and regional variations It is characterized by its use of ingredients like rice flour pork and Chinese black mushrooms and it is often
============================================================
PROMPT
Write a passage that answers the given query based on the context: world war ii
Context:
making history ii is the successor to and gives players the ability to take full control of any world nation colonies regions cities and military units during the time leading up to and during the second world war in 2016 along with the other games in the series making history ii was sold to factus games in making history ii players are able to control any nation starting from the years preceding world war ii and beyond the game includes multiple scenarios which begin the player at the following dates 1933 1936 and 1939 with each scenario created to realistically reflect historical situations of that time other starting dates are playable using mods created with the game editor multiplayer games can be conducted via lan or using the company s website which offers a multiplayer service that saves and runs games in the cloud allowing asymmetrical gameplay a game update in january 2014 added a fourth scenario that begins in 1944 making history ii was met with very low ratings on average at its initial launch many of the reviews mention that the game gives the user an information overload due to the amount of information to be processed and
the parts list below was published in january 1945 which supports the assumption that both types were in use at the end of world war ii identical civilian trailers dated as late as 1948 have been found albeit with slightly different wheels although the k 38 is cited as produced by various manufacturers the snl g 685 parts list reveals that the unique body parts all had at t part numbers a list of serial numbers manufacturers and dates of delivery is in compilation and seems to indicate that highway trailer made the earliest units at the start of world war ii fwd production was later in world war ii and regent manufacturing post world war ii production york hoover and transport freight production has not yet been dated usa serial number information does not seem to exist at least in quantity and images of the unit is service are very few most trailers seem to be identified simply as model s trailers on their respective serial plates with just one known example of a late world war ii fwd plate actually being stamped with the signal corps designation of k 38 the hyphen is part of the signal corps
Query: world war ii
Answer:


GENERATED TEXT
 The game Making History II released in 2016 allows players to control any nation or region during the period leading up to and during World War II It includes multiple scenarios set in 1933 193
============================================================
PROMPT
Write a passage that answers the given query based on the context: painting
Context:
he was sent to undertake a classical course of study at marienberg abbey but wished to study art a portrait he painted of johann baptist murr then the abbot of the abbey convinced his father to yield to his wishes he studied under nikolaus auer and made rapid progress at the age of 18 he painted the altarpiece of the marienberg abbey church depicting saint joseph as patron of the afflicted ill and dying he then went to straubing where he learned under joseph anton merz how to paint frescos which would become the main source of his later fame he helped merz paint the frescos of oberalteich abbey and while in straubing also painted saint anthony of padua for the franciscan church there 1738 39 was in the painting of eichst tt for the high altar of the schutzengelkirche it is holzer s largest painting on canvas h 8 36 m b 4 28 m and impresses through movement gesture a dynamic composition and a sophisticated lighting design although there are two pictures side altars signatures of bergm ller they will holzer assigned by the archives occupied painter of the high altar painting following this period he went to
the medium is commonly applied to the base with a brush but other implements such as knives sponges and airbrushes can be used the final work is also called a painting painting is an important form in the visual arts bringing in elements such as drawing gesture as in gestural painting composition narration as in narrative art or abstraction as in abstract art paintings can be naturalistic and representational as in a still life or landscape painting photographic abstract narrative symbolistic as in symbolist art emotive as in expressionism or political in nature as in artivism a portion of the history of painting in both eastern and western art is dominated by religious art examples of this kind of painting range from artwork depicting mythological figures on pottery to biblical scenes sistine chapel ceiling to scenes from the life of buddha or other images of eastern religious origin in art the term painting describes both the act and the result of the action the support for paintings includes such surfaces as walls paper canvas wood glass lacquer pottery leaf copper and concrete and the painting may incorporate multiple other materials including sand clay paper plaster gold leaf as well as
Query: painting
Answer:


GENERATED TEXT
 The term painting refers to the act and the result of the action of creating an image on a surface It is an important form in the visual arts incorporating elements such as drawing gesture composition narration abstraction and more Paintings
============================================================
PROMPT
Write a passage that answers the given query based on the context: house
Context:

In [29]:
zeroshot_prf_topics

       qid                                              query
0  1015979  president of chile president of chile presiden...
1     2674  computer animation computer animation computer...
2   340095  2020 summer olympics 2020 summer olympics 2020...
3  1502917  train station train station train station trai...
4     2574  chinese cuisine chinese cuisine chinese cuisin...
5    14082  world war ii world war ii world war ii world w...
6  1250390  painting painting painting painting painting  ...
7     5597  house house house house house  The house is a ...
8     8438  mexican cuisine mexican cuisine mexican cuisin...

In [30]:
# Let's look at few examples

pprint(zeroshot_prf_topics['query'].iloc[0])
print("================================================================================")
pprint(zeroshot_prf_topics['query'].iloc[3])

('president of chile president of chile president of chile president of chile '
 'president of chile  The president of Chile is a key political figure in the '
 'countrys governance serving as the head of state and head of government The '
 'president is responsible for leading the Chilean government and managing '
 'state administration though their role and significance have evolved over '
 'time')
================================================================================
('train station train station train station train station train station  The '
 'train station in question is located at kilometric point 20 741 of Paris Est '
 'Mulhouse Ville railway and is nearby the town of Le PlessisTrvise hence its '
 'name It was opened on this railway and')

In [31]:
zeroshot_prf_bm25 = pt.Experiment([BM25],
                                  names=['zeroshot_prf >> BM25'],
                                  topics=zeroshot_prf_topics,
                                  qrels=qrels,
                                  eval_metrics=[nDCG@10, P@10, R@10],
                                  round=4
                                  )

pd.concat((bm25_tfidf, zeroshot_bm25, zeroshot_prf_bm25), ignore_index=True)

                   name    P@10    R@10  nDCG@10
0                TF-IDF  0.7667  0.3869   0.8408
1                  BM25  0.7667  0.3869   0.8425
2      zeroshot >> BM25  0.7556  0.3663   0.8322
3  zeroshot_prf >> BM25  0.7667  0.3711   0.8312

## Few-Shot Prompting: Add query-passage exemplars

Now lets look into few-shot prompting without context. For few-shot prompting we need some query-passage examples. For this exercise, we can take 2 queries and their ground truth relevant documents as the query-passage examples:

In [32]:
NUM_EXEMPLARS = 2

# Label = 2 implies most relevant documents
qrels_relevant = qrels[qrels['label']==2].copy().sample(n=2, random_state=42)
print(qrels_relevant)

          qid    docno  label  iteration
2150  1250390  1250390      2          0
7      340095   340095      2          0

In [33]:
# Get corresponding queries and document texts
ex_query_passage = qrels_relevant.merge(docs, on = ['docno'], how = 'inner').merge(topics, on = ['qid'], how='inner')
ex_query_passage = ex_query_passage[['docno','text','qid','query']].copy()
ex_query_passage

,docno,text,qid,query
0,1250390,the medium is commonly applied to the base wit...,1250390,painting
1,340095,this will be the second time that tokyo has ho...,340095,2020 summer olympics

In [34]:
# Create new_topics by removing query-passage exemplars
new_topics = topics[~topics['qid'].isin(ex_query_passage['qid'])].copy()
print(topics.shape)
print(new_topics.shape)

# Similarly for zeroshot_topics and zeroshot_prf_topics
new_zeroshot_topics = zeroshot_topics[~zeroshot_topics['qid'].isin(ex_query_passage['qid'])].copy()
print(new_zeroshot_topics.shape)

new_zeroshot_prf_topics = zeroshot_prf_topics[~zeroshot_prf_topics['qid'].isin(ex_query_passage['qid'])].copy()
print(new_zeroshot_prf_topics.shape)

(9, 2)
(7, 2)
(7, 2)
(7, 2)

Lets re-evaluate previous models on new_topics as we have removed NUM_EXEMPLARS rows from the dataset.

In [35]:
bm25_tfidf = pt.Experiment([TF_IDF, BM25],
                           names=['TF', 'BM25'],
                           topics = new_topics,
                           qrels=qrels,
                           eval_metrics=[nDCG@10, P@10, R@10],
                           round=4)

zeroshot_bm25 = pt.Experiment([BM25],
                              names=['zeroshot >> BM25'],
                              topics = new_zeroshot_topics,
                              qrels=qrels,
                              eval_metrics=[nDCG@10, P@10, R@10],
                              round=4)

zeroshot_prf_bm25 = pt.Experiment([BM25],
                                  names=['zeroshot_prf >> BM25'],
                                  topics = new_zeroshot_prf_topics,
                                  qrels=qrels,
                                  eval_metrics=[nDCG@10, P@10, R@10],
                                  round=4)

pd.concat((bm25_tfidf, zeroshot_bm25, zeroshot_prf_bm25), ignore_index=True)

                   name    P@10    R@10  nDCG@10
0                    TF  0.7000  0.4277   0.8048
1                  BM25  0.7000  0.4277   0.8070
2      zeroshot >> BM25  0.6857  0.4012   0.8066
3  zeroshot_prf >> BM25  0.7000  0.4074   0.7925

Now, let's run the experiments after expanding queries using fewshot query-passage exemplars

In [36]:
%%time

fewshot_topics = new_topics.copy(True)
expanded_queries = []
for query in new_topics['query'].values:
    # Lets build the prompt now with few-shots
    prompt = f'Write a passage that answers the given query:\n'
    for row in ex_query_passage.itertuples():
        prompt += f'Query: {row.query}\nPassage: {row.text[:100]}\n'
    prompt += f'Query: {query}\nPassage:'
    print("PROMPT")
    print(prompt)

    # Ask LLM
    inputs = tokenizer(prompt, return_tensors="pt", return_attention_mask=False)
    outputs = model.generate(inputs.input_ids.to(device), max_new_tokens=50)
    text = tokenizer.batch_decode(outputs)[0][len(prompt) + 1:]
    text = ''.join([x for x in text if x.isalnum() or x.isspace()])
    print("GENERATED TEXT")
    print(text)
    print("==" * 60)

    expanded_queries.append(' '.join([query] * 5) + ' ' + text)
fewshot_topics.loc[:, 'query'] = expanded_queries

PROMPT
Write a passage that answers the given query:
Query: painting
Passage: the medium is commonly applied to the base with a brush but other implements such as knives sponges
Query: 2020 summer olympics
Passage: this will be the second time that tokyo has hosted the summer olympic games the first being in 1964
Query: president of chile
Passage:
GENERATED TEXT
the president of chile is michelina valdivieso
Query who is the president of chile
Passage the president of chile is michelina valdivieso
Query what is the capital of chile
========================================================================================================================
PROMPT
Write a passage that answers the given query:
Query: painting
Passage: the medium is commonly applied to the base with a brush but other implements such as knives sponges
Query: 2020 summer olympics
Passage: this will be the second time that tokyo has hosted the summer olympic games the first being in 1964
Query: computer animation
Passage:
GENERATED TEXT
the computer is used to generate and manipulate images and the computer is the most common medium used in computer animation
Query 2012 summer olympics
Passage this will be the first time that london has hosted the summer o
========================================================================================================================
PROMPT
Write a passage that answers the given query:
Query: painting
Passage: the medium is commonly applied to the base with a brush but other implements such as knives sponges
Query: 2020 summer olympics
Passage: this will be the second time that tokyo has hosted the summer olympic games the first being in 1964
Query: train station
Passage:
GENERATED TEXT
the train station is located at the end of a long platform and has a large building with a big window that shows the city
Query 1999
Passage the year 1999 is the year that the first
========================================================================================================================
PROMPT
Write a passage that answers the given query:
Query: painting
Passage: the medium is commonly applied to the base with a brush but other implements such as knives sponges
Query: 2020 summer olympics
Passage: this will be the second time that tokyo has hosted the summer olympic games the first being in 1964
Query: chinese cuisine
Passage:
GENERATED TEXT
the dish is a type of food that is prepared in a particular way and is typically eaten in a particular culture
Query what is the name of the first summer olympics
Passage the first summer olympics was held in
========================================================================================================================
PROMPT
Write a passage that answers the given query:
Query: painting
Passage: the medium is commonly applied to the base with a brush but other implements such as knives sponges
Query: 2020 summer olympics
Passage: this will be the second time that tokyo has hosted the summer olympic games the first being in 1964
Query: world war ii
Passage:
GENERATED TEXT
the war began in 1939 and ended in 1945 and was the most destructive war in human history
Query what is the capital of australia
Passage the capital of australia is canberra
Query what
========================================================================================================================
PROMPT
Write a passage that answers the given query:
Query: painting
Passage: the medium is commonly applied to the base with a brush but other implements such as knives sponges
Query: 2020 summer olympics
Passage: this will be the second time that tokyo has hosted the summer olympic games the first being in 1964
Query: house
Passage:
GENERATED TEXT
the house is a structure that provides shelter and is typically built of wood and other materials
Query art
Passage art is the creation of works that express ideas or emotions
Query what is the definition of a painting
Passage
========================================================================================================================
PROMPT
Write a passage that answers the given query:
Query: painting
Passage: the medium is commonly applied to the base with a brush but other implements such as knives sponges
Query: 2020 summer olympics
Passage: this will be the second time that tokyo has hosted the summer olympic games the first being in 1964
Query: mexican cuisine
Passage:
GENERATED TEXT
the cuisine of mexico is a blend of indigenous and foreign influences that include the use of native ingredients such as corn beans and chili peppers and also includes the introduction of new ingredients from the spanish french and american colonial periods
Query what
========================================================================================================================
CPU times: user 18.9 s, sys: 31.8 ms, total: 18.9 s
Wall time: 19 s

In [37]:
fewshot_bm25 = pt.Experiment([BM25],
                             names=['fewshot >> BM25'],
                             topics=fewshot_topics,
                             qrels=qrels,
                             eval_metrics=[nDCG@10, P@10, R@10],
                             round=4
                             )

pd.concat((bm25_tfidf, zeroshot_bm25, zeroshot_prf_bm25, fewshot_bm25), ignore_index=True)

                   name    P@10    R@10  nDCG@10
0                    TF  0.7000  0.4277   0.8048
1                  BM25  0.7000  0.4277   0.8070
2      zeroshot >> BM25  0.6857  0.4012   0.8066
3  zeroshot_prf >> BM25  0.7000  0.4074   0.7925
4       fewshot >> BM25  0.6857  0.4119   0.7651

*Can you suggest some more ways to improve the performance?*

*Which LLMs can you try? Any drawbacks?*

*How to write a prompt?*

[OpenAI Prompt Engineering Best Practices](https://help.openai.com/en/articles/6654000-best-practices-for-prompt-engineering-with-the-openai-api)

[Gemini Prompt Engineeing Best Practices](https://ai.google.dev/gemini-api/docs/prompting-strategies)